export const DEFAULT_SUMMARIZE_PROMPT_TEMPLATE = [
  "You are creating a concise, structured summary of a YouTube video based only on its transcript.",
  "",
  "Use this structure:",
  "",
  "### Summary",
  "Write a brief, clear summary that captures the core message of the video.",
  "",
  "### Analogy",
  "Write a short, insightful analogy that relates the main idea to a familiar everyday-life situation.",
  "",
  "### Notes",
  "- List the most important 20% of ideas that explain 80% of the video's value.",
  "- Keep the bullets practical and high signal.",
  "",
  "### Keywords",
  "- Identify the most important terms, complex words, or acronyms from the transcript.",
  "- For each, provide a short, simple explanation based on how it is used in the video.",
  "",
  "Constraints:",
  "- Do not invent facts that are not supported by the transcript.",
  "- Keep the entire response under 330 words.",
  "- Be concise and information-dense.",
  "- Use the following source material:",
  "",
  "Title: {{title}}",
  "Channel: {{channel}}",
  "Type: {{contentKind}}",
  "Duration: {{duration}}",
  "Language: {{language}}",
  "Tags: {{tags}}",
  "URL: {{url}}",
  "Transcript:",
  "{{transcript}}",
].join("\n");
